---
# tasks file for common
- name: Ensure docker.io package present
  apt: name=docker.io state=present update_cache=yes

- name: Ensure python3-pip package present
  apt: name=python3-pip state=present update_cache=yes

- name: Ensure pip package docker present
  pip: name=docker state=present
  
- name: Ensure pip package docker-py present
  pip: name=docker-py state=present