---
# tasks file for bildContainer
- name: create build directory
  file:
    path: /tmp/buildDoker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copy Dockerfile
  copy:
    src: ./Dockerfile
    dest: /tmp/buildDoker/Dockerfile
    owner: root
    group: root
    mode: '0644'

- name: build container image
  docker_image:
    name: tomcat1:v1
    source: build
    build:
    path: /tmp/buildDoker
    state: present
