---
# tasks file for bildContainer
- name: create build directory
  file: path={{dest_folder}} state=directory mode=0755

- name: copy Dockerfile
  copy: src=Dockerfile dest={{ dest_folder }}/Dockerfile mode=0555


- name: build container image
  docker_image:
    name: tomcat1:v1
    source: build
    build:
      path: {{dest_folder}}
    state: present
